export const USER_FETCHED = 'USER_FETCHED';
export const TOKEN_VALIDATED = 'TOKEN_VALIDATED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const FORGOT_PASSWORD_EMAIL_SENDED = 'FORGOT_PASSWORD_EMAIL_SENDED';
export const FORGOT_PASSWORD_EMAIL_LOADING = 'FORGOT_PASSWORD_EMAIL_LOADING';
export const FORGOT_PASSWORD_EMAIL_LOADED = 'FORGOT_PASSWORD_EMAIL_LOADED';
