export const MUSIC_PUBLIC = 'MUSIC_PUBLIC';
export const MUSIC_PENDING = 'MUSIC_PENDING';
export const MUSIC_REVISION = 'MUSIC_REVISION';
export const MUSIC_ARCHIVED = 'MUSIC_ARCHIVED';
export const MUSIC_SHARED = 'MUSIC_SHARED';
export const MUSIC_SOLD = 'MUSIC_SOLD';
